### ISSUE TITLE
2 of my 3 fans are shown

### ISSUE THREAD

**Issue by BananaAcid** [Rem0o/FanControl.DellPlugin#11]
one is missing :) Precision T3610

**Comment by Dumpflam** [comment]
mine is a dell tower precision t3600 not 3610 like yours. the fans are kinda like on and off its 634rpm until 67% where it ramps up to maximum... and i can only control my cpu gpu and "1st intake fan from the top" i cannot control the bottom two intake fans.
the fans aren't proportional like i said they're kinda like on and off... help please, i installed this mainly for my cpu and i need proportional fan adjustment if possibble.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
