### ISSUE TITLE
Does this support all Dell laptops?

### ISSUE THREAD

**Issue by Majixed** [Rem0o/FanControl.DellPlugin#13]
I own a Dell G15 gaming laptop and I didn't like Alienware command center, so I'd like to know if this will work here. Thank you

**Comment by Rem0o** [comment]
Tested personally only on two different models, but for sure it doens't work on "all" laptops. There is only one way to find out in your case, test it.

**Comment by Majixed** [comment]
Whoops, just saw that it uses DellFanManagement, which didn't allow me to manually set the fan speed when I tried it earlier. I asked about it in a Discord server and they said it was a recent BIOS update that restricted this.
