### ISSUE TITLE
The effect of  UpgradedSystem

### ISSUE THREAD

**Issue by shadowZlh** [Rem0o/FanControl.DellPlugin#14]
I have some questions 
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"UpgradedSystem"=dword:00000000
```
I don't know what does this do, can you tell me ? And I've read that link, but didn't understand what's in it,
I've used DellFanCmd to control my fan ,It does not require modifying the regedit,

And my English is poor , Please excuse me
Thanks a lot

**Comment by Rem0o** [comment]
The link in the README is no longer valid.

WebArchive for the win: https://web.archive.org/web/20211121044820/http://forum.notebookreview.com/threads/dellfanmanagement-dellfankeepalive-%E2%80%93-tools-for-managing-the-fan-speed-in-dell-laptops.833340/
