### ISSUE TITLE
two intake fans dont show up dell precision t3600 tower

### ISSUE THREAD

**Issue by Dumpflam** [Rem0o/FanControl.DellPlugin#15]
mine is a dell tower precision t3600. the fans are kinda like on and off its 634rpm until 67% where it ramps up to maximum... and i can only control my cpu gpu and "1st intake fan from the top" i cannot control the bottom two intake fans.
the fans aren't proportional like i said they're kinda like on and off... help please, i installed this mainly for my cpu and i need proportional fan adjustment and the bottom two intake fans if possibble.

**Comment by Dumpflam** [comment]
oke i just read a closed issue and turns out its only off low and high so yeah but i still dont know why i dont have the two intake fans

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
