### ISSUE TITLE
Does this support Alienware desktop R13?

### ISSUE THREAD

**Issue by liangvinusc** [Rem0o/FanControl.DellPlugin#16]
I've been attempting to integrate the plugin with [FanControl.Releases](https://github.com/Rem0o/FanControl.Releases), but it appears that the system is unable to detect any sensors. Does this support Alienware desktop R13? Thanks!

**Comment by Rem0o** [comment]
Dell/Alienware desktops don't use usual fan control chips, and so are not supported natively.

See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
