### ISSUE TITLE
Error " Dell could not initialise or has no sensors"

### ISSUE THREAD

**Issue by Kijicode** [Rem0o/FanControl.DellPlugin#17]
Hi, 

I already unblocked all of the plugin files in the plugin folder.
Is there anything else I can try?
Fancontrol only recognises my GPU fan and none of the 2 tower fans.

It's a Dell G5 5090 desktop PC

Thanks in advance!

![fancontroll](https://github.com/user-attachments/assets/fdb5d51d-ccd5-4735-939a-ebf111153cb1)

**Comment by Rem0o** [comment]
This you do the [special note](https://github.com/Rem0o/FanControl.DellPlugin#special-note) ?

**Comment by Kijicode** [comment]
Thanks for your swift reply. 
Total noob here - Could you please be a bit more specific?
Which one of the options would you suggest that I try?

Is it this registry change? 
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"UpgradedSystem"=dword:00000000

**Comment by Kijicode** [comment]
Hi, sorry for the extremely late reply!
I ended up buying a new non-Dell PC, so this issue can be closed.
But thanks for your help and have a nice day!
