### ISSUE TITLE
Dell Laptops Percesion Not Working

### ISSUE THREAD

**Issue by wisamidris7** [Rem0o/FanControl.DellPlugin#19]
![image](https://github.com/user-attachments/assets/4f65720e-d1f3-412e-b83d-47c455c850b8)

I use this gpu
![image](https://github.com/user-attachments/assets/66a6c002-cbcf-4370-ae91-7fc56489697b)

And I need a help how to make it work cause look that

![image](https://github.com/user-attachments/assets/f42e1cbd-8bfa-4894-9d19-7a32176f16ac)
 Zero RPM

Could you give me steps if i'm missing things or if there a software that will make me be able to control my fan

And Thanks!

**Comment by Rem0o** [comment]
Did you create the registry key indicated here and rebooted?
https://github.com/Rem0o/FanControl.DellPlugin#special-note

**Comment by wisamidris7** [comment]
Even with adding the registry key into there

Still not working

![image](https://github.com/user-attachments/assets/4cf6dacb-715a-4454-a0f9-f0bb6c6bbd14)

Also I allowed it from windows secuirty

![image](https://github.com/user-attachments/assets/96f619e6-2111-4a2c-9174-74d348b827c4)

**Comment by Rem0o** [comment]
Then I am sorry but I don't have anything else to try.

**Comment by wisamidris7** [comment]
Thanks for your hard work and have a good time.
