### ISSUE TITLE
Fans only ever seem to kick in at >=40%

### ISSUE THREAD

**Issue by JamesYeoman** [Rem0o/FanControl.DellPlugin#3]
My fan curve is set to be a minimum of 20%, but the fans only seem to kick in when 40% is reached on the curve. This is substantial, as it means it'll go from 0% to 40% with no ramp-up, which not only makes it very irritating from a noise perspective, but makes the spikes in temperature very frequent

**Comment by Rem0o** [comment]
Thats because there is no gradual control on dell fans. There is only three available speeds. Off, low and high.
