### ISSUE TITLE
[Idea] PWM-style fan management?

### ISSUE THREAD

**Issue by JamesYeoman** [Rem0o/FanControl.DellPlugin#4]
Would it be possible to take inspiration from PWM? Alternation between Off and Low for 0-50% fan, and alternation between Low and High for 50-100% fan? Or would such a suggestion need to be made to the DellFanManagement library directly?

**Comment by Rem0o** [comment]
It would need to be made by DellFanManagement, but you can't do that. It's not made for that at all, you wouldn't be able to get a fast enough duty cycle.
