### ISSUE TITLE
FanControl does not start when using the FanControl.DellPlugin.dll

### ISSUE THREAD

**Issue by Babur-Ahmed** [Rem0o/FanControl.DellPlugin#8]
This is the log

https://pastebin.com/1DYXrLWu

I tried unblocking every file present in FanControl's folders but the issue did not resolve

**Comment by KHVBui** [comment]
Problem is still present.

**Comment by DanielB09** [comment]
got the same problem

**Comment by otherside1** [comment]
Same Problem

**Comment by otherside1** [comment]
You have to copy all the files in the download not just one
